eureka:
  client: 
    shouldFetchRegistry: false
  instance:
    port: 5000
spring:
  cloud:
    discovery:
      registrationMethod: direct
mysql: 
  client: 
    database: mydatabase
    username: username
    password: password    
